### ISSUE TITLE
Support for Classifier

### ISSUE THREAD

**Issue by mcqueenorama** [emicklei/artreyu#1]
I don't see support for classifier:

https://maven.apache.org/plugins/maven-deploy-plugin/examples/deploying-with-classifiers.html

It looks like it would need to be added to Model and the cli options and any path/filename building code.  It may overlap in functionality with the OS CLI option.  

What do you think?

**Comment by emicklei** [comment]
hi, 

Classifiers, yes, I thought about that when designing this tool.
The short answer is that I did not needed them so I left them out.

The artifacts I needed to assemble in my projects are actually "final" sub products. For example, I have one Java project that produces its own one-jar artifact (using maven), that maven-assembled artitfact is then compressed and uploaded to Nexus using artreyu. The custom dependencies (Java libraries) its uses are build using other Maven jobs; they use Nexus and maven layout with classifiers support (no artreyu here).

All other Jenkins jobs for non-Java sub-products have their own custom build scripts (based on make and Docker) and produce compressed archive files (tgz). I introduced the OS "classifier" because I have sub-products that are compiled for OSX or Linux and others that are OS independent (docs, Java,...).

I guess you want classifiers to avoid having mulitple descriptors (on for each type) per project. Would it make sense to allow multiple types for the **type** field in the descriptor that causes multiple calls of artreyu-nexus?

**Comment by mcqueenorama** [comment]
I don't know.  I'll think about it a bit more.

**Comment by emicklei** [comment]
@mcqueenorama are you working on the plugin idea you suggested a while ago?

**Comment by mcqueenorama** [comment]
Not yet but I intend to. It's lower priority than my other projects right
now.

**Comment by emicklei** [comment]
i will close this issue now. Feel free to reopen anytime when you stumble upon this.
